name: 'Bci Migration Agent'
description: 'Update microservices from older spring versions to spring 3.x '
author: "Daniel Carvajal"
runs:
  using: "composite"
  steps:
    # Step 1: Checkout current repository
    - name: Checkout Repository
      uses: actions/checkout@v3
    # Step 2: Define local variables   
    - name: Define local variables
      run: |
        DOCKER_IMAGE="danielcarvajal2178/migration-agent:lastest"
        DOCKER_CONTAINER="migration-agent"   
      shell: bash    
    # Step 3: Print input parameters
    - name: Print input parameters
      run: | 
        echo "The input parameters: 
          - Microservice name:  ${{ inputs.parametro1 }}
          - Branch name: ${{ inputs.parametro2 }}
          - Secret token: $REPO_TOKEN_SECRET
          - Variable token: $REPO_TOKEN_VARIABLE "
      shell: bash    
    # Step 4: Pull Doker image
    - name: Pull Docker Image
      run: |
        echo "Pulling Docker image $DOCKER_IMAGE"
        docker pull $DOCKER_IMAGE
      shell: bash  
    # Step 5: Run Doker image
    - name: Run Docker Container
      run: |
        # Convert environment variables into Docker-compatible -e options
        declare -a ENV_ARGS=('-e ${{ inputs.parametro1 }}' '-e ${{ inputs.parametro2 }}' '-e $REPO_TOKEN_SECRET')

        # Run the container with the provided runtime arguments
        echo "Running container $DOCKER_CONTAINER with image $DOCKER_IMAGE"
        docker run -d --name $DOCKER_CONTAINER $ENV_VARS $DOCKER_IMAGE
      shell: bash  
    # Step 6: Verify running containers
    - name: Verify Running Containers
      run: docker ps
      shell: bash  
    # Step 7: Clean up docker container
    - name: Clean Up Docker Container
      run: docker rm -f $DOCKER_CONTAINER
      shell: bash

