name: 'Bci Migration Agent'
description: 'Update microservices from older spring versions to spring 3.x '
author: "Daniel Carvajal"
# Optional: visual configurations to actions of Marketplace
branding:
  icon: 'package' # icon name (consulta FontAwesome)
  color: 'blue' # color list: white, yellow, blue, green, orange, red, purple, etc.    
runs:
  using: "composite"
  steps:
      # Step 1: Checkout the action
    - name: Checkout the action
      uses: jdanieldeveloper/migration-agent@main
    # Step 2: echo hello action
    - name: Greet
      run: echo "Hello action"
      shell: bash
