name: 'Bci Migration Agent'
description: 'Update microservices from older spring versions to spring 3.x '
author: "Daniel Carvajal"
# Optional: visual configurations to actions of Marketplace
branding:
  icon: 'package' # icon name (consulta FontAwesome)
  color: 'blue' # color list: white, yellow, blue, green, orange, red, purple, etc.    
runs:
  using: "composite"
  steps:
    # Step 1: Checkout current repository
    - name: Checkout this repository
      uses: actions/checkout@v3
    # Step 2: echo hello action
    - name: Greet
      run: | 
        echo "Los parametro de entrada fueron: 
          - microservice name: $param1
          - branch name: $param2 
          - secret token: $REPO_TOKEN_SECRET 
          - variable token: $REPO_TOKEN_SECRET "
      shell: bash
