name: Migration agent action test
on:
  workflow_dispatch: # Execute de manual workflow
   inputs:
      param1:
        description: "Microservice name"
        required: true
        default: "Ex: ms-test-name"
      param2:
        description: "Branch name"
        required: true
        default: "Ex: branch-test-123"
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout the action
        uses: jdanieldeveloper/migration-agent@main        
      # Step 2: Set environment variables and secrets
      - name: Set secrets and variables
        env:
          REPO_TOKEN_SECRET: ${{ secrets.REPOSITORY_TOKEN_SECRET }}
          REPO_TOKEN_VARIABLE: ${{ vars.REPOSITORY_TOKEN_VARIABLE }} 
      # Step 3: Run the custom action
      - name: Run the custom action
        uses: ./      
        with:
          param1: ${{ inputs.input1 }}
          param2: ${{ inputs.input2 }}