name: Execute Migration Agent
on:
  workflow_dispatch: # Execute de manual workflow
   inputs:
      param1:
        description: "Microservice name"
        required: true
        default: "Ex: ms-test-name"
      param2:
        description: "Branch name"
        required: true
        default: "Ex: branch-test-123"
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 3: Run the custom action
      - name: Run the custom action
        uses: ./
        with:
          parametro1: ${{ inputs.param1 }}
          parametro2: ${{ inputs.param2 }}
        env:
          REPO_TOKEN_SECRET: ${{ secrets.REPOSITORY_TOKEN_SECRET }}
          REPO_TOKEN_VARIABLE: ${{ vars.REPOSITORY_TOKEN_VARIABLE }}  